version: '3'
services:
  my-java-app:
    image: amazoncorretto:20-alpine3.18-full
    volumes:
      - ./app:/app
    working_dir: /app
#    command: ./gradle run -t --args="-mortadelo -filemon"
    command: tail -f /dev/null
    ports:
      - "8080:8080"
