# Utiliza una imagen base de Ubuntu
FROM ubuntu:latest

# Actualiza los repositorios e instala OpenJDK
RUN apt-get update -y && apt-get install -y openjdk-19-jdk-headless

# Establece la versión de Java a utilizar
#ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64
#ENV PATH $JAVA_HOME/bin:$PATH

# Configura el directorio de trabajo
WORKDIR /app