/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mutiitu.blog.java;

import org.junit.Test;

import com.mutiitu.framework.core.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
